/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2025-09-23 17:36:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>E-commerce Demo - WAF Training App</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }\n");
      out.write("        .header { background-color: #333; color: white; padding: 20px; text-align: center; }\n");
      out.write("        .nav { background-color: #555; padding: 10px; }\n");
      out.write("        .nav a { color: white; text-decoration: none; margin: 0 15px; }\n");
      out.write("        .nav a:hover { text-decoration: underline; }\n");
      out.write("        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }\n");
      out.write("        .card { background: white; border-radius: 8px; padding: 20px; margin: 10px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }\n");
      out.write("        .search-box { width: 100%; max-width: 400px; padding: 10px; border: 1px solid #ddd; border-radius: 4px; }\n");
      out.write("        .btn { background-color: #007bff; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; }\n");
      out.write("        .btn:hover { background-color: #0056b3; }\n");
      out.write("        .feature-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"header\">\n");
      out.write("        <h1>E-commerce Demo Application</h1>\n");
      out.write("        <p>Sample Web Application for WAF Training & Testing</p>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"nav\">\n");
      out.write("        <a href=\"/ecommerce/\">Home</a>\n");
      out.write("        <a href=\"/ecommerce/products\">Products</a>\n");
      out.write("        <a href=\"/ecommerce/search\">Search</a>\n");
      out.write("        <a href=\"/ecommerce/cart\">Cart</a>\n");
      out.write("        <a href=\"/ecommerce/user\">Account</a>\n");
      out.write("        <a href=\"/ecommerce/admin\">Admin</a>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"card\">\n");
      out.write("            <h2>Welcome to the E-commerce Demo</h2>\n");
      out.write("            <p>This is a sample e-commerce web application designed for transformer-based WAF training and testing.</p>\n");
      out.write("            \n");
      out.write("            <div style=\"text-align: center; margin: 20px 0;\">\n");
      out.write("                <form action=\"/ecommerce/search\" method=\"get\">\n");
      out.write("                    <input type=\"text\" name=\"q\" class=\"search-box\" placeholder=\"Search for products...\">\n");
      out.write("                    <button type=\"submit\" class=\"btn\">Search</button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"feature-grid\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h3>ðï¸ Product Catalog</h3>\n");
      out.write("                <p>Browse through various product categories including Electronics, Books, and Appliances.</p>\n");
      out.write("                <a href=\"/ecommerce/products\" class=\"btn\">Browse Products</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h3>ð Shopping Cart</h3>\n");
      out.write("                <p>Add products to your cart and proceed to checkout with our secure payment system.</p>\n");
      out.write("                <a href=\"/ecommerce/cart\" class=\"btn\">View Cart</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h3>ð¤ User Account</h3>\n");
      out.write("                <p>Create an account, login, and manage your profile and order history.</p>\n");
      out.write("                <a href=\"/ecommerce/user\" class=\"btn\">My Account</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h3>ð Advanced Search</h3>\n");
      out.write("                <p>Search for products with filters, sorting, and advanced query options.</p>\n");
      out.write("                <a href=\"/ecommerce/search\" class=\"btn\">Search Products</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h3>ð Order Management</h3>\n");
      out.write("                <p>Track your orders, view order history, and manage shipping information.</p>\n");
      out.write("                <a href=\"/ecommerce/orders\" class=\"btn\">My Orders</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h3>âï¸ Admin Panel</h3>\n");
      out.write("                <p>Admin interface for managing products, orders, and users (admin login required).</p>\n");
      out.write("                <a href=\"/ecommerce/admin\" class=\"btn\">Admin Panel</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"card\">\n");
      out.write("            <h3>ð¤ WAF Training Information</h3>\n");
      out.write("            <p>This application is designed to generate diverse HTTP traffic patterns for training transformer-based Web Application Firewalls:</p>\n");
      out.write("            <ul>\n");
      out.write("                <li><strong>GET Requests:</strong> Product browsing, search queries, pagination</li>\n");
      out.write("                <li><strong>POST Requests:</strong> User registration, login, cart operations, order processing</li>\n");
      out.write("                <li><strong>Form Submissions:</strong> Contact forms, checkout process, user profile updates</li>\n");
      out.write("                <li><strong>AJAX Requests:</strong> Dynamic content loading, search suggestions</li>\n");
      out.write("                <li><strong>File Uploads:</strong> Profile pictures, product images</li>\n");
      out.write("                <li><strong>Session Management:</strong> Login/logout, shopping cart persistence</li>\n");
      out.write("                <li><strong>Parameter Variations:</strong> Query strings, form data, JSON payloads</li>\n");
      out.write("            </ul>\n");
      out.write("            <p>The application includes various endpoints that accept different types of input to create comprehensive training data for anomaly detection models.</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"card\">\n");
      out.write("            <h3>ð Quick Links for Testing</h3>\n");
      out.write("            <p>Common endpoints for generating traffic:</p>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"/ecommerce/products?category=Electronics&sort=price_asc\">Filtered Product Listing</a></li>\n");
      out.write("                <li><a href=\"/ecommerce/search?q=laptop&category=electronics&min_price=500\">Advanced Search</a></li>\n");
      out.write("                <li><a href=\"/ecommerce/products/1\">Product Details</a></li>\n");
      out.write("                <li><a href=\"/ecommerce/user/login\">Login Page</a></li>\n");
      out.write("                <li><a href=\"/ecommerce/user/register\">Registration Page</a></li>\n");
      out.write("                <li><a href=\"/ecommerce/cart?action=add&product_id=1&quantity=2\">Add to Cart</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div style=\"text-align: center; margin-top: 40px; color: #666;\">\n");
      out.write("        <p>&copy; 2025 E-commerce Demo - WAF Training Application</p>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
